Fix issue #83
justkawal/excel pull request #218
Opened 2023-03-13 18:50 UTC by amigne

I propose the following patch to fix the issue #83.

2023-03-13 19:02 UTC, FauconSpartiate approved these changes
LGTM

2023-03-14 14:05 UTC, justkawal requested changes
LGTM after the changes

2023-03-14 18:01 UTC, justkawal approved these changes
LGTM

2023-03-14 18:32 UTC, FauconSpartiate approved these changes

2023-03-15 12:14 UTC, merged